smtp:
  address:              "smtp.gmail.com"
  port:                 587
  domain:               'gmail.com'
  user_name:            'e.shopping.master@gmail.com'
  password:             'e-shopping'
  authentication:       'plain'
  enable_starttls_auto:  true
regexp:
  email: \A[0-9a-z][_.0-9a-z-]{0,31}@([0-9a-z][0-9a-z-]{0,30}[0-9a-z]\.){1,4}[a-z]{2,4}\z
